### ISSUE TITLE
SONG_18 - Sonic the Fighters issue (M2MidiDec)

### ISSUE THREAD

**Issue by cglmrfreeman** [ValleyBell/MidiConverters#7] opened 2020-01-01 00:13 UTC
Greetings,

All the songs extracted from Sonic the Fighters appear to be correct except for "SONG_18", which in the OST is labeled as "MISSION COMPLETE - Egg Fanfare" and labeled internally in the game as "0xAE1018".

I'm not sure what's going on with it, but it should sound more like it's OST counterpart than it currently does as extracted by the current build: https://www.youtube.com/watch?v=XNQZFSxCXhI

The extracted MIDI with Sonic the Fighters soundfont converted to WAV is attached for reference.
[SONG_18.zip](https://github.com/ValleyBell/MidiConverters/files/4013657/SONG_18.zip)

**Comment by ValleyBell** [comment] 2020-01-01 09:48
Good catch! I can confirm that somehow the instrument initialization block is missing.

I had a quick look at the ROM and I think the issue is this line: https://github.com/ValleyBell/MidiConverters/blob/2eb17c0f54d0c8c71d28a049895a4d36973c17db/M2MidiDec.c#L738
Change that from `>=` to `>` and it should work.

Explanation:
In all of the songs, in "Segment 1" (in the MIDI), it has MIDI command `A0 07 xx` where `xx` makes the sound driver initialize instruments from a global table.
SONG_18 has `A0 07 16` here, thus loading instrument block 0x16.

The number of song initialization blocks is specified as 0x16 (see epr-19021.31 ROM, offset 0x80B2).
However, that number seems to be the highest valid ID, or `(count-1)`.
The converter assumes it's `(count)`, so it won't load the instrument data for this song.

I guess this might be a good chance to touch the converter, update and fix it.

**Comment by cglmrfreeman** [comment] 2020-01-02 03:09
A suggestion for the converter might be to support Virtua Fighter 2, which was built on the same engine as StF and VF. But that's not really relevant to this issue but may not be extremely difficult to implement given you have most of the code down and just need to research what needs modifying.

**Comment by ValleyBell** [comment] 2020-03-30 18:03
The bug is fixed by 8b66704be05a5bdb55d83c2a8d10028449637b27.

**Closed by ValleyBell** 2020-03-30 18:03 UTC

**Comment by ValleyBell** [comment] 2020-05-16 08:53
> A suggestion for the converter might be to support Virtua Fighter 2, which was built on the same engine as StF and VF. But that's not really relevant to this issue but may not be extremely difficult to implement given you have most of the code down and just need to research what needs modifying.

I added support for more games in a7556bdcbc0400e3182cdc3b95d01fd4491c4daf.
Virtua Fighter 2 is not supported though, because it uses a different sound driver version and data pointers are at different locations.
